diff --git a/core/tests/Drupal/FunctionalTests/Bootstrap/UncaughtExceptionTest.php b/core/tests/Drupal/FunctionalTests/Bootstrap/UncaughtExceptionTest.php
index 1a0f19e971..c485277483 100644
--- a/core/tests/Drupal/FunctionalTests/Bootstrap/UncaughtExceptionTest.php
+++ b/core/tests/Drupal/FunctionalTests/Bootstrap/UncaughtExceptionTest.php
@@ -274,6 +274,7 @@ public function testLoggerException() {
 
     // Find fatal error logged to the error.log
     $errors = file(\Drupal::root() . '/' . $this->siteDirectory . '/error.log');
+    throw new \Exception(var_export($errors, true));
     $this->assertIdentical(count($errors), 8, 'The error + the error that the logging service is broken has been written to the error log.');
     $this->assertTrue(strpos($errors[0], 'Failed to log error') !== FALSE, 'The error handling logs when an error could not be logged to the logger.');
 
@@ -303,6 +304,7 @@ protected function assertErrorLogged($error_message) {
     }
 
     $content = file_get_contents($error_log_filename);
+    throw new \Exception(var_export($content, true));
     $rows = explode(PHP_EOL, $content);
 
     // We iterate over the rows in order to be able to remove the logged error
